### ISSUE TITLE
Incompatible with IDEA 2020.01

### ISSUE THREAD

**Issue by ronhks** [chathurabuddi/intellij-jasper-report-support#15]
The plugin incompatible with IDEA 2020.01.

**Comment by slestak** [comment]
Working on a PR for this.

**Comment by slestak** [comment]
https://github.com/chathurabuddi/intellij-jasper-report-support/pull/16

**Comment by chathurabuddi** [comment]
Hi @ronhks , @slestak ,

Please note that the pull request #16 was merged and released with v1.0.2. 
Refer #18 for more details.

**Comment by ronhks** [comment]
@chathurabuddi thanks!
